/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatRounds: typeof import('./src/components/ChatRounds.vue')['default']
    CommonFooter: typeof import('./src/components/CommonFooter.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    ContentCard: typeof import('./src/components/ContentCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    HomePageAlert: typeof import('./src/components/HomePageAlert.vue')['default']
    MessageCard: typeof import('./src/components/MessageCard.vue')['default']
    MyButtons: typeof import('./src/components/MyButtons.vue')['default']
    MyCollapse: typeof import('./src/components/MyCollapse.vue')['default']
    MyDropdown: typeof import('./src/components/MyDropdown.vue')['default']
    MyTextArea: typeof import('./src/components/MyTextArea.vue')['default']
    PuzzleCard: typeof import('./src/components/PuzzleCard.vue')['default']
    PuzzlePage: typeof import('./src/components/PuzzlePage.vue')['default']
    PuzzleShow: typeof import('./src/components/PuzzleShow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
